supp Average Trip Duration YoY Display = 
VAR Difference =
    [supp Average Trip Duration YoY %]
VAR RoundedDifference =
    ROUND(Difference * 100, 1)
VAR Arrow =
    SWITCH(
        TRUE(),
        RoundedDifference > 0, "▲",
        RoundedDifference < 0, "▼",
        "⟶"
    )
RETURN
    IF(
        ISBLANK(Difference),
        BLANK(),
        Arrow & " " & FORMAT(ABS(RoundedDifference), "0.0") & "%"
    )